
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kikdcvyhuwrqfovlgrer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpa2RjdnlodXdycWZvdmxncmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDc4ODMsImV4cCI6MjA2MTYyMzg4M30.4xhiuSFAz8Duw2DEkLdekrpCOLJWY8Jrn82s9WaN2W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

export const auth = supabase.auth;
